apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-devops-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-devops-project
  template:
    metadata:
      labels:
        app: simple-devops-project
    spec:
      containers:
      - image: techvault2024/simple-devops-image
        name: simple-devops-image
        ports:
        - containerPort: 8080
