apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-devops-project-deployment
  name: simple-devops-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-devops-project-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-devops-project-deployment
    spec:
      containers:
      - image: techvault2024/simple-devops-image
        imagePullPolicy: Always
        name: simple-devops-image
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
