apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-devops-project-deployment
  name: simple-devops-project-deployment
spec:
  ports:
  - nodePort: 31200
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-devops-project-deployment
  type: LoadBalancer
~                     
